---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name:
      - software-properties-common
      - curl
      - git
      - unzip
      - acl
    state: present

- name: Set timezone
  timezone:
    name: UTC
