---
- name: Create WordPress directory
  file:
    path: /var/www/wordpress
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Download WordPress
  get_url:
    url: "https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz"
    dest: /tmp/wordpress.tar.gz
    mode: '0644'

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy WordPress files
  copy:
    src: /tmp/wordpress/
    dest: /var/www/wordpress
    remote_src: yes
    owner: www-data
    group: www-data
    mode: '0755'

- name: Create WordPress wp-config.php file
  template:
    src: wp-config.php.j2
    dest: /var/www/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'

- name: Set correct permissions on WordPress directory
  shell: find /var/www/wordpress -type d -exec chmod 755 {} \; && find /var/www/wordpress -type f -exec chmod 644 {} \;
  args:
    warn: false
    
- name: Install wp-cli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: '0755'

- name: Set up WordPress using wp-cli
  shell: |
    cd /var/www/wordpress
    wp core install --url={{ wordpress_site_url }} --title="{{ wordpress_site_title }}" --admin_user={{ wordpress_admin_user }} --admin_password={{ wordpress_admin_password }} --admin_email={{ wordpress_admin_email }} --skip-email --allow-root
  args:
    creates: /var/www/wordpress/.wp-install-complete
  become_user: www-data
  
- name: Create installation complete file
  file:
    path: /var/www/wordpress/.wp-install-complete
    state: touch
    owner: www-data
    group: www-data
